// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProject5.Infrastucture.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniProject5.Infrastucture.Migrations
{
    [DbContext(typeof(FinancialCompanyContext))]
    [Migration("20241120015350_updatetable1")]
    partial class updatetable1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniProject5.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Deptno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("deptno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Deptno"));

                    b.Property<string>("Deptname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deptname");

                    b.Property<int?>("Location")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationNavigationId")
                        .HasColumnType("integer");

                    b.Property<int?>("Mgrempno")
                        .HasColumnType("integer")
                        .HasColumnName("mgrempno");

                    b.Property<int?>("Spvempno")
                        .HasColumnType("integer")
                        .HasColumnName("spvempno");

                    b.HasKey("Deptno");

                    b.HasIndex("LocationNavigationId");

                    b.HasIndex("Mgrempno");

                    b.HasIndex("Spvempno");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Dependent", b =>
                {
                    b.Property<int>("Dependentno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dependentno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Dependentno"));

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<int?>("Empno")
                        .HasColumnType("integer")
                        .HasColumnName("empno");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relationship");

                    b.Property<string>("Sex")
                        .HasColumnType("character varying")
                        .HasColumnName("sex");

                    b.HasKey("Dependentno");

                    b.HasIndex("Empno");

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Empno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Empno"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("address");

                    b.Property<int?>("Deptno")
                        .HasColumnType("integer")
                        .HasColumnName("deptno");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Employeetype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employeetype");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fname");

                    b.Property<DateTime?>("Lastupdateddate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastupdateddate");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lname");

                    b.Property<int?>("Nik")
                        .HasColumnType("integer")
                        .HasColumnName("nik");

                    b.Property<int?>("Phonenumber")
                        .HasColumnType("integer")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position");

                    b.Property<int?>("Salary")
                        .HasColumnType("integer")
                        .HasColumnName("salary");

                    b.Property<string>("Sex")
                        .HasColumnType("character varying")
                        .HasColumnName("sex");

                    b.Property<string>("Status")
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<string>("Statusreason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statusreason");

                    b.HasKey("Empno");

                    b.HasIndex("Deptno");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.HasKey("Id");

                    b.ToTable("location");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Projno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("projno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Projno"));

                    b.Property<int?>("Deptno")
                        .HasColumnType("integer")
                        .HasColumnName("deptno");

                    b.Property<int?>("LocationNavigationId")
                        .HasColumnType("integer");

                    b.Property<int?>("Projectlocation")
                        .HasColumnType("integer");

                    b.Property<string>("Projname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projname");

                    b.HasKey("Projno");

                    b.HasIndex("Deptno");

                    b.HasIndex("LocationNavigationId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Workson", b =>
                {
                    b.Property<int>("Empno")
                        .HasColumnType("integer")
                        .HasColumnName("empno");

                    b.Property<int>("Projno")
                        .HasColumnType("integer")
                        .HasColumnName("projno");

                    b.Property<DateOnly>("Dateworked")
                        .HasColumnType("date")
                        .HasColumnName("dateworked");

                    b.Property<int?>("Hoursworked")
                        .HasColumnType("integer")
                        .HasColumnName("hoursworked");

                    b.HasKey("Empno", "Projno")
                        .HasName("workson_pkey");

                    b.HasIndex("Projno");

                    b.ToTable("workson");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Department", b =>
                {
                    b.HasOne("MiniProject5.Domain.Entities.Location", "LocationNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("LocationNavigationId");

                    b.HasOne("MiniProject5.Domain.Entities.Employee", "MgrempnoNavigation")
                        .WithMany("DepartmentMgrempnoNavigations")
                        .HasForeignKey("Mgrempno");

                    b.HasOne("MiniProject5.Domain.Entities.Employee", "SpvempnoNavigation")
                        .WithMany("DepartmentSpvempnoNavigations")
                        .HasForeignKey("Spvempno");

                    b.Navigation("LocationNavigation");

                    b.Navigation("MgrempnoNavigation");

                    b.Navigation("SpvempnoNavigation");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("MiniProject5.Domain.Entities.Employee", "EmpnoNavigation")
                        .WithMany("Dependents")
                        .HasForeignKey("Empno");

                    b.Navigation("EmpnoNavigation");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Employee", b =>
                {
                    b.HasOne("MiniProject5.Domain.Entities.Department", "DeptnoNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("Deptno");

                    b.Navigation("DeptnoNavigation");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Project", b =>
                {
                    b.HasOne("MiniProject5.Domain.Entities.Department", "DeptnoNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("Deptno");

                    b.HasOne("MiniProject5.Domain.Entities.Location", "LocationNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("LocationNavigationId");

                    b.Navigation("DeptnoNavigation");

                    b.Navigation("LocationNavigation");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Workson", b =>
                {
                    b.HasOne("MiniProject5.Domain.Entities.Employee", "EmpnoNavigation")
                        .WithMany("Worksons")
                        .HasForeignKey("Empno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("workson_empno_fkey");

                    b.HasOne("MiniProject5.Domain.Entities.Project", "ProjnoNavigation")
                        .WithMany("Worksons")
                        .HasForeignKey("Projno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("workson_projno_fkey");

                    b.Navigation("EmpnoNavigation");

                    b.Navigation("ProjnoNavigation");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Employee", b =>
                {
                    b.Navigation("DepartmentMgrempnoNavigations");

                    b.Navigation("DepartmentSpvempnoNavigations");

                    b.Navigation("Dependents");

                    b.Navigation("Worksons");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Location", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MiniProject5.Domain.Entities.Project", b =>
                {
                    b.Navigation("Worksons");
                });
#pragma warning restore 612, 618
        }
    }
}
